=== pc8192/com.qx.io.xml/input/schema2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
 xmlns:xs="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://s8.com"
 xmlns:tns="http://s8.com"
 elementFormDefault="qualified">
	<xs:element name="test" type="tns:com.s8.lang.xml.tests.example01.Wrapper"/>

	<xs:complexType name="com.s8.lang.xml.tests.example01.TestClass4">
		<xs:sequence>
		<xs:choice maxOccurs="unbounded" minOccurs="1">
			<xs:element name="user_user" type="tns:com.s8.lang.xml.tests.example01.User" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="user" type="tns:com.s8.lang.xml.tests.example01.User" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
		</xs:sequence>
		<xs:attribute name="toto" type="xs:string"/>
		<xs:attribute name="b" type="xs:string"/>
	</xs:complexType>

	<xs:complexType name="com.s8.lang.xml.tests.example01.TestClass3">
		<xs:attribute name="toto" type="xs:string"/>
	</xs:complexType>

	<xs:complexType name="com.s8.lang.xml.tests.example01.Module">
		<xs:attribute name="b2" type="xs:string"/>
	</xs:complexType>

	<xs:complexType name="com.s8.lang.xml.tests.example01.User">
		<xs:sequence>
		<xs:choice maxOccurs="unbounded" minOccurs="1">
			<xs:element name="note" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
		</xs:sequence>
		<xs:attribute name="toto" type="xs:string"/>
		<xs:attribute name="password" type="xs:string"/>
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>

	<xs:complexType name="com.s8.lang.xml.tests.example01.Wrapper">
		<xs:sequence>
		<xs:choice maxOccurs="unbounded" minOccurs="1">
			<xs:element name="ee" type="tns:com.s8.lang.xml.tests.example01.TestClass3" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="item_ee2" type="tns:com.s8.lang.xml.tests.example01.TestClass4" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="ee2" type="tns:com.s8.lang.xml.tests.example01.TestClass4" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="field" type="tns:com.s8.lang.xml.tests.example01.Module" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="module" type="tns:com.s8.lang.xml.tests.example01.Module" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="item_ee" type="tns:com.s8.lang.xml.tests.example01.TestClass3" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="field_module" type="tns:com.s8.lang.xml.tests.example01.Module" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
		</xs:sequence>
		<xs:attribute name="factor" type="xs:string"/>
	</xs:complexType>

	<xs:complexType name="com.s8.lang.xml.tests.example01.TestClass2">
		<xs:sequence>
		<xs:choice maxOccurs="unbounded" minOccurs="1">
			<xs:element name="ee" type="tns:com.s8.lang.xml.tests.example01.TestClass3" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="item_ee2" type="tns:com.s8.lang.xml.tests.example01.TestClass4" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="ee2" type="tns:com.s8.lang.xml.tests.example01.TestClass4" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="field" type="tns:com.s8.lang.xml.tests.example01.Module" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="module" type="tns:com.s8.lang.xml.tests.example01.Module" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="item_ee" type="tns:com.s8.lang.xml.tests.example01.TestClass3" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="field_module" type="tns:com.s8.lang.xml.tests.example01.Module" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
		</xs:sequence>
		<xs:attribute name="b2" type="xs:string"/>
		<xs:attribute name="factor" type="xs:string"/>
	</xs:complexType>
</xs:schema>

=== pc8192/com.qx.io.xml/input/test02.xml
<?xml version="1.0" encoding="UTF-8"?>
<test xmlns="http://s8.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://s8.com schema2.xsd" factor="5">
	<module b2="76" />
	<ee toto="72" />
	<item_ee toto="45" />
	<item_ee toto="46" />
	<ee2 toto="47">
		<user name="directly-set-user" />
		<user name="zijeiojz"></user>
	</ee2>
	<item_ee2 toto="48" b="3">
		<user name="ojo" />
		<user name="ojo1" password="rekhejj" />
		<user name="ojo2" password="rekhejj" />
		<user name="ojo3" password="rekhejj">
			<note>this user is special</note>
		</user>
		<user name="ojo4" password="rekhejj" />
	</item_ee2>
	<field></field>
	<item_ee />
</test>
